# Workflow to publish the package to npm on creating a new release

name: Publish Package
on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org
          cache: yarn

      # # - name: Install dependencies
      #   run: yarn install
      # - name: Build package
      #   run: npm run build

      - uses: simenandre/publish-with-yarn@v2
        with:
          npm-auth-token: ${{ secrets.NPM_TOKEN }}
